services:
  - type: web
    name: kingsqueen-downloader
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn app:app
